### ISSUE TITLE
QA copy for new goggles on-boarding

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#154]
- [ ] Overall messaging appropriateness and effectiveness as part of larger campaign (on-boarding)
- [ ] Proper spelling, grammar and punctuation
- [ ] Proper use of Mozilla Foundation style guide
- [ ] Links work and have proper calls to action

File your feedback as issues within this repo and make sure it goes in the Webmaker On-boarding milestone.

/cc @HPaulJohnson

**Comment by secretrobotron** [comment]
Here's the design so far: https://redpen.io/rw825a9bece366d9ed

@edrushka @HPaulJohnson: need to brainstorm some ideas to go in place of the obvious "Lorem Ipsum"s here.

**Comment by secretrobotron** [comment]
Ready to review: https://webmaker.mofostaging.net/en-US/goggles

**Comment by edrushka** [comment]
Now that I see it on staging, I have 2 comments.
1 - Don't think we need to italicize 'source'
2 - In the second box, I'd prefer to be consistent with the video and use the term "install" instead of "set up". And Lainie was right, the wording here is kind of awkward. I'd nix "on the Internet". So this copy would read: "Install the X-ray Goggles and get the power to view and edit the code behind any website.

These suggestions aren't blockers, IMO. I realize that Lucy already made the video, so her screencap would have to be updated if we implemented these. Might be too much work. @HPaulJohnson ?

**Comment by secretrobotron** [comment]
Thanks @edrushka ! Changes made.
Good call on the video. @LucyeoH agreed to re-record it once everything was put together.

Closing this. @HPaulJohnson can re-open if there's more to consider.

**Comment by HPaulJohnson** [comment]
Thanks, all, and sorry I'm late to this review. Everything looks good to me. 

Only question is re: the video - at the end we say watch my next video to hack the news. How does a user navigate to or find that video?

**Comment by secretrobotron** [comment]
@HPaulJohnson atm, it's just on the same youtube channel. we could put it below, perhaps, or make a youtube list that auto-plays to the next one.
