### ISSUE TITLE
Create copy for new goggles on-boarding

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#157]
https://redpen.io/evbc175a75cee1325e
- [ ] need header
- [ ] need to check instructions

![goggles_landing](https://cloud.githubusercontent.com/assets/53411/5911222/c07efb76-a590-11e4-95c0-8ac5bc33b4be.png)

/cc @edrushka @HPaulJohnson

**Comment by secretrobotron** [comment]
cc @xmatthewx

**Comment by edrushka** [comment]
Hey! I already put copy suggestions in an old redpen.

**Comment by secretrobotron** [comment]
- step two of landing page should read "Click the background image"

**Comment by xmatthewx** [comment]
@edrushka @HPaulJohnson - Thanks for suggestions. They're integrated in the new, [simplified design](https://redpen.io/rw825a9bece366d9ed). 

We need a 2-3 word header such as "Hack any webpage"

![goggles_landing](https://cloud.githubusercontent.com/assets/53411/5911222/c07efb76-a590-11e4-95c0-8ac5bc33b4be.png)

**Comment by secretrobotron** [comment]
from @edrushka and @HPaulJohnson:
- "Remix this page"
- last sentence of the bottom box: "Set up x-ray goggles [linked] and get the power to view and edit the code behind any website on the internet."

**Comment by amirad** [comment]
Some copy suggestions:

*Change title to "Edit this page" (remix is often a term people don't understand or resonate with)
*"Set up X-Ray Goggles so that you can have the power to view and edit the code behind any website on the internet" (would bold or underline 'any website on the internet') OR would use "Learn how to get the power to view and edit the code behind any website with X-Ray Goggles. Check out our tutorials and activities."

**Comment by edrushka** [comment]
@amirad We considered "edit this page" and "change this page" but decided that it might actually look like an error (as if placeholder text somehow made it to prod)!

**Comment by ldecoursy** [comment]
Learn how X-Ray Goggles give you the power to view and edit the code behind any website. (Not sure we need "on the internet.")

I think it's ok to try "remix" for now - we definitely use that instead of "hack". Another option might be "Change this page using code."
