### ISSUE TITLE
[Feature request] Save external resources with makes

### ISSUE THREAD

**Issue by nathanathan** [mozilla/goggles.webmaker.org#173]
I tried sharing a make with some colleagues to get feedback on some design changes I made to a webpage that I was running on a temporary web-server, but the make broke because the css files were not available once I took the server down. Furthermore, many websites frequently change their css and images, so makes will have a short shelf-life if they rely on the original resources. I think saving the external resources or embedding them using things like data urls would be a major improvement to this tool.

**Comment by Pomax** [comment]
This is mosty due to technical reasons: we save makes as single files, so we would not only have to download resource files, but also somehow intelligently inline them. While it might seem that downloading and inlining single CSS files is easy, CSS actually allows for very complex networks for files that would all need to be resolved (think of @import and @font-face rules), which makes downloading assets like these quite difficult. Unfortunate as it can be in situations like these, the choice to keep those files "on the web" instead of storing them with the make is intentional.

**Comment by nathanathan** [comment]
@Pomax have you considered using code from [a css minifier](https://github.com/jakubpawlowicz/clean-css) to handle the `@import` rules? `@font-face` resources could be transformed into data-uris. It wouldn't be easy, but I hope you will consider leaving this issue open as a goal to aspire to one day, as I believe we agree on the utility of the feature.

**Comment by Pomax** [comment]
it's not going to be a thing we'll be planning for, but as an open source project if someone is willing to take on that task because they thing it's worth their time, we'll be more than happy them get what they come up with merged into what we have (if possible, of course. We're currently in the process of analysing which parts of goggles are hitting the "this needs a proper rewrite" stage)
