### ISSUE TITLE
X-Ray Goggles Won't Load on IE

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/goggles.webmaker.org#199]
Complaint via email user can't access new goggles page when using IE. 

STR: 
1. Go to goggles.webmaker.org
Expected: Redirect to - https://webmaker.org/en-US/goggles
Actual: White screen emerges and the page will not load. They found the scripting error in the screen shot below whilst using IE8.
![ieerrorpage](https://cloud.githubusercontent.com/assets/8070833/6710948/5af62846-cd5a-11e4-9b76-c87e6eb6500d.png)

Lucy gave them the new URL: https://webmaker.org/en-US/goggles and they had the same problem. 
STR: 
1. Went to https://webmaker.org/en-US/goggles
Expected: Goggles page emerges
Actual: White screen appeared and the page wouldn't load. Same error message as above. 

They claim it happens on on all IE versions, ones we have tested are IE8 and IE11 so far.

Whenever anyone tries to access the website it just continues to load but never fully loads and displays the webpage.

**Comment by LucyeoH** [comment]
cc. @jbuck @secretrobotron

**Comment by LucyeoH** [comment]
Also can someone add the labels "bug" and "help report". Don't have access to labels for this repo.

**Comment by Pomax** [comment]
hmm, I'm not sure we support IE8, since it's not HTML5 compatible. It's also been abandoned by Microsoft now (this happened when XP stopped being supported, on which note: Windows XP has been abandoned by Microsoft, too, unless you pay them a few million a year for private support).

That said, a redirect alone shouldn't lead to a blank screen. I've tested this on IE10 and IE11 (both are modern enough to support HTML5 and modern Javascript calls), and for what it's worth both of those work fine for me. I do not see any script errors getting generated on either direct pageload or redirect from goggles.webmaker.org

**Comment by simonwex** [comment]
Closing as we don't support IE8 for goggles.
