### ISSUE TITLE
Compile feedback from user testing at MozFest

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#253]
**Notes for user feedback on install and FTU**
- Install: The term 'Bookmark' is confusing because it is usually used for saving sites. Because goggles is using it for something else, it is confusing. People also go stuck on the view bookmark bar step.
- FTU: Activate goggles step points to the bookmark bar but not at the exact location of the goggles bookmark so it is confusing.
- Too much text. Kids just skim and won't read. Suggested to use more gifs.
- FTU wording: in the Remix the Images step we say "Hover over any of the animal sections..." but now it's just one image container so we should update copy to reflect.
- FTU: they like the note about copyright law

**Goggles UI**
- no one uses short cut keys (didn't even realize they where there )
- hint text at the bottom right is not noticeable enough and could be more useful
- goggles needs to work on low bandwidth (for some reason a page shows as loading when user clicks on the image when everything should already be pre-loaded) - filled in #252

**Teaching Activities**
- Hack the News: we should use a kids news site instead of the times (too serious and can have some harsh images), or we could use a art gallery or museum site (something with a lot of images), or a music/band site - Bieber may have been mentioned :)

**Other**
- we should teach that the work 'hack' is not sinister (some parents get concerned when they see it)
- we could reference a site that helps people host images (ex postimage.org)
- there is an opportunity to drive to and educate about advocacy (maybe in an activity)

**Comment by kristinashu** [comment]
@hannahkane @Pomax please add any notes you have to the above comment.

**Comment by hannahkane** [comment]
Awesome notes, @kristinashu. I only walked through the exercise with a few people, and most of my observations and their comments are reflected in the above list already. A couple additional notes:

 * One person said that this activity seemed like it would only appeal to children, but I think that's exactly who we're targeting with this activity. I think it's useful to narrow in on that audience for the FTU, though, of course, Goggles can be useful to people of all ages.
 * One person felt we overpromised in our description of what Goggles could do. They expected to be able to "make a real webpage with anything they wanted." Re-reading the description on the landing page, I'm not sure what we could do to manage expectations about the limited functionality. Wondering if anyone else heard this feedback, or if it can be considered an outlier.
 * Will add some suggested copy changes in a follow-up comment.
 * I wouldn't expect anyone to use the shortcut keys, since we don't make them obvious. (I don't think I know them all.) I'm not sure we need to include this in the FTU experience, though I would like to provide more cues for the user in the regular Goggles experience. Will file separate ticket about that.
 * Love the idea of a more kid-friendly news site. Perhaps @chadsansing would have ideas?
 * My understanding is that we've faced the "hack" terminology problem before. @KevZawacki - any suggestions for how we can keep the fun/catchiness of "Hack the News" but make it sound less scary/illegal? Maybe "Remix the News"?
 * Love the idea of helping ppl understand image hosting services, but, again, I don't think the FTU activity is the right place for that. @chadsansing - do we have other activities that get at that issue?

**Comment by hannahkane** [comment]
Copy suggestions to fix a couple errors, to address some of the items in the first comment, and to standardize "X-Ray Goggles" as opposed to "The X-Ray Goggles," which I've noticed we use sometimes in written form, though I've rarely heard anybody use the definite article when referring to it in spoken language. (cc @KevZawacki - if you agree, let's always refer to Goggles as X-Ray Goggles or simply Goggles, but never "The" X-Ray Goggles)

**Tutorial** 

Learn about the key features of X-Ray Goggles by mixing and matching different dinosaur, fox, and bird sections, to create a new web page featuring your original animal creation.

**Activate X-Ray Goggles** [note: removed "the"]

Click on X-Ray Goggles in your bookmark toolbar to activate them. By the way: you can do this on any website!

To deactivate, just press 'esc' on your keyboard at any time

If you haven't installed X-Ray Goggles yet, click here to go to the install page.

**Remix the Images**

Hover over the image to highlight it, then click them to open the code in the Goggles editor.

**Make a New Animal!**

Play around by swapping the words dinosaur, fox, and bird in each section.

Click the Update button to save your changes.

(You can also use a completely different image! When using Goggles, you can add any image from anywhere on the Web, but be sure to respect copyright law: just because you can find an image does not mean you're automatically free to use it for your own purposes!)

**Comment by chadsansing** [comment]
@hannahkane, there are all sorts of young-student-facing news sites we could pull from; I'd like to create a 'new' Hack the News page to package with a workshop/training project on Thimble, as well, so let me prototype something or work with someone to do so in the near future. Maybe during the week before Orlando.

Several Thimble projects have image search and reverse-image search baked into tutorials, but we could make another one specifically for Web X-Ray Goggles as part of an effort to update the activities on the landing page. Would love to help in the near future!

**Comment by kristinashu** [comment]
@hannahkane if we've learned anything from the movie The Social Network it is to remove the 'the'.

I've updated the FTU comps: https://invis.io/F44O6ZJGY 

**Intro/Activate**
- I got pretty ruthless with the copy and removed the first intro step so we can jump right into the instructions. Let me know if you think we should put it back. 
- Removed "Skip Tutorial". Users can still click the x (top left corner) to skip the tutorial.
- Removed the note about 'esc' since a note shows up once they are activated and users can always access it through the UI buttons.
- Made the activate step a lightbox instead of a bubble so that the pointer doesn't throw people off (still have the gif to show uses where to activate).

**Make a New Animal!**
- updated "dinosaur" to "dino" so that it is slightly shorter
- made the copyright text fine print so it's is more bonus content than instructions

I'll update the install page now as well. Thinking of added a 'view bookmark toolbar' step.

**Comment by hannahkane** [comment]
@kristinashu - lol.

+1 to removing Tutorial page entirely. Great idea.

One more small edit to **Remix the Images**: Hover over the image to highlight it, then click [remove: them] to open the code in the Goggles editor.

**Comment by hannahkane** [comment]
@chadsansing - awsm, and thanks. We'll update the Hack the News activity, and add any more Goggles-specific activities, whenever you have them.

**Comment by KevZawacki** [comment]
@hannahkane I support "Remix" over "Hack." I believe we've even referred to the activity in the past as "Remix the News." 

And let's definitely stylize as "X-Ray Goggles (no "the").

**Comment by hannahkane** [comment]
Looks so good. Really love the new treatment for the Activity on the install page.

**Comment by kristinashu** [comment]
I think these are done:
FTU: https://invis.io/F44O6ZJGY
Install page: https://redpen.io/p/qv1c96b69ffec76998

@cassiemc do you want to take a look?

**Comment by cassiemc** [comment]
I love it @kristinashu. Really nice illustration on the install page, I suspect that will work really well. Hopefully users scroll down to see it (something we should pay attention to). Suggested a small tweak wrt color. Also want to note, it would still be great on the FTU if the bubbles floated up and down to draw the eye. Nice work!

**Comment by kristinashu** [comment]
Thanks @cassiemc I've updated the illustration colours https://redpen.io/p/qv1c96b69ffec76998

@Pomax do you have any user feedback to add?
